# Generated by Django 4.2.3 on 2023-07-27 20:55

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("Logo", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Engine_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("Role", models.CharField(max_length=50, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="showroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("Location", models.CharField(max_length=50)),
                ("Owner", models.CharField(max_length=50)),
                ("Staff", models.ManyToManyField(to="Showroom.staff")),
            ],
        ),
        migrations.CreateModel(
            name="model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "images",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location=pathlib.PureWindowsPath(
                                "D:/code files/aws_mzr/Django/assignment#22/media"
                            )
                        ),
                        upload_to="",
                    ),
                ),
                (
                    "Brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Showroom.brand",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="engine",
            fields=[
                ("name", models.CharField(max_length=50)),
                (
                    "Engine_no",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Showroom.engine_model",
                        verbose_name="Engine model name",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="car",
            fields=[
                (
                    "Chasis_no",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "Engine",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Showroom.engine",
                    ),
                ),
                ("Features", models.ManyToManyField(to="Showroom.feature")),
                (
                    "model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Showroom.model",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="brand",
            name="showrooms",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Showroom.showroom",
            ),
        ),
    ]
