# Generated by Django 4.2.3 on 2023-07-28 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Showroom", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="Engine",
        ),
        migrations.RemoveField(
            model_name="car",
            name="Features",
        ),
        migrations.AddField(
            model_name="model",
            name="Engine",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model_model",
                to="Showroom.engine",
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="Features",
            field=models.ManyToManyField(related_name="models", to="Showroom.feature"),
        ),
        migrations.AlterField(
            model_name="engine",
            name="model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model",
                to="Showroom.engine_model",
                verbose_name="Engine model name",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="Brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="Showroom.brand",
            ),
        ),
    ]
