# Generated by Django 4.2.3 on 2023-07-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Showroom",
            "0002_remove_car_engine_remove_car_features_model_engine_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="showroom",
            name="contact",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
